---
sudo: required
dist: bionic
services:
  - docker
cache:
  directories:
    - vendor/bundle
rvm:
  - 2.6.0
addons:
  apt:
    sources:
      - sourceline: "deb [trusted=yes] https://packages.chef.io/repos/apt/stable bionic main"
        key_url: "https://packages.chef.io/chef.asc"
    packages:
      - chefdk
      - python-pip
env:
  global:
    - CHEF_LICENSE=accept
    - secure: gN9V9u6SJXtEo3l8DCl/bjr22X3Tg+JQFNigYUaZLj686L5jc+n8I3LDffPTpGcCfm0IxFSsQq0pW3mXKGGbav4ccG6ft+WbQVGELc/M3/kvMhwtATlAd4743Zbo7ynFVHxXbDPvteaCi/CVmU3sFbIml6awhrce0qnf42JxXt3MROaqomyAQXqi8/6+MdAaMwfIu/67GFHdO4ra2VIEGUDkJBqQXMJ29NXYcItfmfdGTAujZH4slTkbHFxWWEDkNbprm3/0rdjiNj/Xz3myHfXUwPenKmm9uOGxD5t9/pStWa5Q9rUWTYKONPMsOamoKKcaB6xxG7Nye5LG1gMoMvv0xq5N0mw68mWSsOG/aI1IDsdOWPmmk1pP8WL0mqMzMIEOeMxyZpKVMjusPRu/KSq2vJrWz5U9Yl1MCUxXM+fcS5VpCeWnSSlYTrzF703PN8FrgA8Guxb2xQIzJMvTuOX7xepqIX56k6QrcDSb4i7tAkPnHCCGrGOyau75itTLwuINonBOZcD8586pmGgzO86V+UKg3nNHduDDEAuw78gfOXNKFe0Osx5ufusF2DSHunHS723DXzC6R9TS2SlqtT7ingww3SD65A8v9824y0SDUHAEQKxu3a3J1p8h1yksAoPgwe7XLPfr/PBt6gONClAy/ezEP+kQxxkfSV3f2TE=
    - secure: PcWh1lEuy2hadGAQVLBtDa/oMgXGeTwK9bwcYtZYGUV8AKvGn+j7CheH6dN7tzh0TRraxM0qiyTIiZa0ipcKie4eK5wi+iw/MlO19CjveejJ3j6cSgZy93NVfHq4V2rvLe98QSbZpTsCreUn9zqTbFqWAcDMDignF8NesJfo4mlu+pkhJoEPXBlhLLNeUyP3YB0KqHJliYO1hHp+t2br63+AL686tKRERmwwiMdN2qA6SxCHMaGflZEnmOV8XpBKxlRyo4x1f4juhZPBv2IEKbWHDNMTagz51geAlINaWZqyQl2z5btGuGY4la11jLk0F1jFw5E+IQ+pfnKj6cbrrIDrS6ArjX/DIY4nsxFU160hd862M7YrhNvhfRMCvqnpLsyyKiir47WWJcRrjWpkMJMRkbWZ+lNsug4s3JGxHUZL7ZVGrUCucmRzSxDpGG+dXeTUQRTeyc80ebpDP/9qWKWm53Pje9cCwIyj9dn9hwKR6EBKo8B96igugX8z2B0BeB43JwdlveQBaIa64zLclNfWsGwrHMgR9WEuGwzhjP0MKK6sFslEJZHa7DjHZFI2pVf7BF795tUUDPTa5T1XCsydARQAHbS+cmzySX8Q8uGzUP0RKAaxbwbdeZMmOb+1cOjGPmY5p2yrOkbblDEHaWogakIPTSoFO/LZtit75to=
  matrix:
    - INSTANCE=default-ubuntu-1804
    - INSTANCE=all-options-ubuntu-1804
    - INSTANCE=default-with-shoryuken-and-fullstaq-ubuntu-1804
    - INSTANCE=http-unicorn-apache-hanami-resque-ubuntu-1804
    - INSTANCE=s3-thin-nginx-padrino-delayed-job-ubuntu-1804
    - INSTANCE=nullified-ubuntu-1804
    - INSTANCE=maximum-override-ubuntu-1804
before_install:
  - gem install bundler
install:
  - pip install --user yamllint
  - chef exec bundle install --jobs=5 --retry=5
before_script:
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"
  - chef exec bundle exec overcommit --sign
  - chef exec bundle exec overcommit --sign pre-commit
  - ruby test/integration/update_data_bag.rb
script:
  - chef exec bundle exec overcommit -r
  - chef exec bundle exec rspec
  - travis_retry chef exec bundle exec rake integration:docker[${INSTANCE}]
